name: Run Jest Unit Testing

on: 
  pull_request :
    branches: 
      -  uat
    paths:
      - 'src/**'
jobs:
  Run_Unit_Test:     
     runs-on: ubuntu-latest 
     strategy:
      matrix:
        node-version: [12.x]

     steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build With Ant
        run: ant -noinput -buildfile build.xml -v

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install --save-dev jest
      - run: npm install --save-dev ts-jest
      - run: npm install tslint typescript --save-dev
      - run: npm install tslint typescript -g
      - run: npm install tslint-sonarts --save-dev
      - run: npm install sonarqube-scanner --save-dev
      - run: npm run build --if-present
      - run: npm test
      - run: npm test -- --coverage    
     
        env:
          CI: true
